#!/usr/bin/env bash
# scripts/sync-assets.sh

set -euo pipefail


# ============================================================
# ASSET SYNC
#
# Safe default:
#
#   ASSET_STAGE=dev
#
# PROD mutation requires:
#
#   ASSET_STAGE=prod
#   ASSET_CONFIRMATION=SYNC-PROD
#
# Read-only target validation:
#
#   ASSET_DRY_RUN=1
#
# Infrastructure identifiers are resolved from CloudFormation.
# No bucket IDs are read from local .env files.
# ============================================================


SCRIPT_NAME="sync_assets"

REPO_ROOT="$(
  git rev-parse --show-toplevel 2>/dev/null ||
    pwd
)"

cd "${REPO_ROOT}"


LOG_DIR="${REPO_ROOT}/logs/${SCRIPT_NAME}"

mkdir -p "${LOG_DIR}"


# ============================================================
# LOG RETENTION
# ============================================================

if compgen -G "${LOG_DIR}/${SCRIPT_NAME}_"*.log >/dev/null; then
  ls -1t "${LOG_DIR}/${SCRIPT_NAME}_"*.log |
    tail -n +31 |
    while read -r file; do
      rm -f "${file}"
    done
fi


RUN_TS="$(
  date +%Y-%m-%d_%H-%M-%S
)"

LOG_FILE="${LOG_DIR}/${SCRIPT_NAME}_${RUN_TS}.log"

LATEST_LOG="${LOG_DIR}/${SCRIPT_NAME}_latest.log"


# ============================================================
# HELPERS
# ============================================================

die() {
  echo "❌ $*" >&2
  exit 1
}


info() {
  echo "ℹ️  $*"
}


ok() {
  echo "✅ $*"
}


require_cmd() {
  command -v "$1" >/dev/null 2>&1 ||
    die "Missing required command: $1"
}


exec \
  > >(tee -a "${LOG_FILE}" "${LATEST_LOG}") \
  2>&1


trap '
  rc=$?

  if [[ ${rc} -eq 0 ]]; then
    echo "✅ RESULT: SUCCESS"
  else
    echo "❌ RESULT: FAILED (exit=${rc})"
  fi
' EXIT


# ============================================================
# PRECONDITIONS
# ============================================================

require_cmd git
require_cmd aws


git rev-parse \
  --is-inside-work-tree \
  >/dev/null 2>&1 ||
  die "Not inside a Git repository."


# ============================================================
# CONFIGURATION
# ============================================================

ASSET_STAGE="${ASSET_STAGE:-dev}"

ASSET_DRY_RUN="${ASSET_DRY_RUN:-0}"

ASSET_CONFIRMATION="${ASSET_CONFIRMATION:-}"

# Heavy asset sources
SPRITES_DIR="${ASSETS_DIR:-src/assets/ships/sprites}"
SPRITES_PREFIX="${ASSETS_PREFIX:-ships/sprites/}"

GLB_DIR="${GLB_DIR:-src/assets/ships/glb}"
GLB_PREFIX="${GLB_PREFIX:-ships/glb/}"

# Geo dataset generated by build-geo-dataset.mjs
GEO_FILE="${GEO_FILE:-public/geo/major_cities.v1.json}"
GEO_KEY="${GEO_KEY:-geo/major_cities.v1.json}"

REGION="${AWS_REGION:-us-east-1}"

PROFILE="${AWS_PROFILE:-}"


case "${ASSET_STAGE}" in

  dev)
    STACK_NAME="AssetsCdnStackDev"
    ;;


  prod)
    STACK_NAME="AssetsCdnStack"
    ;;


  *)
    die "Unsupported ASSET_STAGE '${ASSET_STAGE}'. Use 'dev' or 'prod'."
    ;;

esac


# ============================================================
# PROD SAFETY
#
# Fail before authentication or infrastructure discovery for
# any real PROD mutation.
#
# Read-only dry runs intentionally do not require confirmation.
# ============================================================

if [[ "${ASSET_STAGE}" == "prod" &&
      "${ASSET_DRY_RUN}" != "1" &&
      "${ASSET_CONFIRMATION}" != "SYNC-PROD" ]]; then

  echo ""
  echo "❌ PROD asset sync blocked."
  echo ""
  echo "To explicitly sync PROD:"
  echo ""
  echo "  ASSET_STAGE=prod \\"
  echo "  ASSET_CONFIRMATION=SYNC-PROD \\"
  echo "  npm run sync:assets"
  echo ""

  exit 1
fi


# ============================================================
# AWS COMMAND
# ============================================================

AWS_PROFILE_ARGS=()


if [[ -n "${PROFILE}" ]]; then
  AWS_PROFILE_ARGS=(
    --profile
    "${PROFILE}"
  )
fi


aws_cli() {
  aws \
    "${AWS_PROFILE_ARGS[@]}" \
    "$@"
}


# ============================================================
# AWS SESSION
# ============================================================

ensure_aws_session() {

  if aws_cli \
    sts \
    get-caller-identity \
    >/dev/null 2>&1; then

    return 0
  fi


  if [[ -n "${PROFILE}" ]]; then

    info "AWS session unavailable. Attempting SSO login for '${PROFILE}'..."

    aws \
      sso \
      login \
      --profile "${PROFILE}"


    aws_cli \
      sts \
      get-caller-identity \
      >/dev/null 2>&1 ||
      die "Unable to authenticate to AWS after SSO login."


    return 0
  fi


  die "AWS authentication unavailable. Set AWS_PROFILE or authenticate using the default credential chain."
}


# ============================================================
# CONTEXT
# ============================================================

echo ""

info "Log file: ${LOG_FILE}"
info "Asset stage: ${ASSET_STAGE}"
info "Stack: ${STACK_NAME}"
info "Sprites: ${SPRITES_DIR}"
info "GLB: ${GLB_DIR}"
info "Geo dataset: ${GEO_FILE}"
info "Region: ${REGION}"
info "AWS profile: ${PROFILE:-<default>}"

echo ""


ensure_aws_session


# ============================================================
# RESOLVE STACK OUTPUTS
# ============================================================

info "Resolving asset infrastructure from CloudFormation..."


RESOLVED_STAGE="$(
  aws_cli \
    cloudformation \
    describe-stacks \
    --region "${REGION}" \
    --stack-name "${STACK_NAME}" \
    --query "Stacks[0].Outputs[?OutputKey=='Stage'].OutputValue | [0]" \
    --output text
)"


BUCKET="$(
  aws_cli \
    cloudformation \
    describe-stacks \
    --region "${REGION}" \
    --stack-name "${STACK_NAME}" \
    --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue | [0]" \
    --output text
)"


GEO_BUCKET="$(
  aws_cli \
    cloudformation \
    describe-stacks \
    --region "${REGION}" \
    --stack-name "${STACK_NAME}" \
    --query "Stacks[0].Outputs[?OutputKey=='GeoBucketName'].OutputValue | [0]" \
    --output text
)"


# ============================================================
# STAGE VALIDATION
#
# AssetsCdnStack is the pre-P4 existing PROD stack. Until the
# P4 infrastructure migration is deployed, it does not yet
# contain the new Stage output.
#
# Missing Stage is therefore accepted ONLY for the exact legacy
# PROD stack. DEV must always expose Stage=dev.
# ============================================================

if [[ -z "${RESOLVED_STAGE}" ||
      "${RESOLVED_STAGE}" == "None" ]]; then

  if [[ "${ASSET_STAGE}" == "prod" &&
        "${STACK_NAME}" == "AssetsCdnStack" ]]; then

    RESOLVED_STAGE="prod"

    info "Stage output is not present on the existing PROD stack yet."
    info "Treating AssetsCdnStack as legacy PROD during the P4 migration."

  else

    die "Stage output was not found in ${STACK_NAME}."

  fi
fi


if [[ "${RESOLVED_STAGE}" != "${ASSET_STAGE}" ]]; then

  die "Stage mismatch: requested '${ASSET_STAGE}', stack reported '${RESOLVED_STAGE}'."

fi


if [[ -z "${BUCKET}" ||
      "${BUCKET}" == "None" ]]; then

  die "BucketName output was not found in ${STACK_NAME}."
fi


if [[ -z "${GEO_BUCKET}" ||
      "${GEO_BUCKET}" == "None" ]]; then

  die "GeoBucketName output was not found in ${STACK_NAME}."
fi


ok "Resolved ${ASSET_STAGE} asset bucket."

echo ""
echo "Target:"
echo "  Stage:        ${RESOLVED_STAGE}"
echo "  Stack:        ${STACK_NAME}"
echo "  Asset bucket: ${BUCKET}"
echo "  Geo bucket:   ${GEO_BUCKET}"
echo ""


# ============================================================
# READ-ONLY DRY RUN
# ============================================================

if [[ "${ASSET_DRY_RUN}" == "1" ]]; then

  ok "Dry run complete. No S3 objects were changed."

  exit 0
fi


# ============================================================
# SOURCE VALIDATION
# ============================================================

if [[ ! -d "${SPRITES_DIR}" ]]; then
  die "Required sprite directory does not exist: ${SPRITES_DIR}"
fi


# ============================================================
# SPRITES
# ============================================================

echo ""

info "Publishing ship sprites..."


aws_cli \
  s3 \
  sync \
  "${SPRITES_DIR}" \
  "s3://${BUCKET}/${SPRITES_PREFIX}" \
  --region "${REGION}" \
  --exclude "*/top/*" \
  --cache-control "public,max-age=86400" \
  --only-show-errors


ok "Sprite publication complete."


# ============================================================
# GLB
#
# GLB output is optional. The repository currently does not
# contain src/assets/ships/glb, so absence must not fail CD.
# ============================================================

echo ""


if [[ -d "${GLB_DIR}" ]]; then

  info "Publishing GLB assets..."


  aws_cli \
    s3 \
    sync \
    "${GLB_DIR}" \
    "s3://${BUCKET}/${GLB_PREFIX}" \
    --region "${REGION}" \
    --cache-control "public,max-age=86400" \
    --only-show-errors


  ok "GLB publication complete."

else

  info "No GLB directory found; skipping ${GLB_DIR}."

fi


# ============================================================
# GEO DATASET
#
# The generated dataset is optional during migration. If the
# tracked/generated file exists, publish it to the dedicated
# geo bucket.
# ============================================================

echo ""


if [[ -f "${GEO_FILE}" ]]; then

  info "Publishing geo dataset..."


  aws_cli \
    s3 \
    cp \
    "${GEO_FILE}" \
    "s3://${GEO_BUCKET}/${GEO_KEY}" \
    --region "${REGION}" \
    --content-type "application/json" \
    --cache-control "public,max-age=86400" \
    --only-show-errors


  ok "Geo dataset publication complete."

else

  info "Geo dataset not found; skipping ${GEO_FILE}."

fi


# ============================================================
# RESULT
# ============================================================

echo ""

ok "Asset publication complete."

echo ""
echo "Stage:        ${ASSET_STAGE}"
echo "Asset bucket: ${BUCKET}"
echo "Geo bucket:   ${GEO_BUCKET}"
echo ""